name: use node.js
on: push
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0 
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
      - run: npm install
      - run: npm run build
      
