name: hello-world
on: push
jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - run: echo "$(cat hello_world.txt)"
  my-job:
    # Importing a reusable workflow from another repository and branch
    uses: dmangasorg/TestrepoOrg/.github/workflows/build-test-deploy.yml@main
    # Passing 'node-version' as an input parameter to the reusable workflow
    with:
      node-version: '18.x'
